apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-servicemonitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: fastapi
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
